gesture swipe left 4 i3-msg workspace prev
gesture swipe right 4 i3-msg workspace next
gesture swipe left 3 i3-msg focus left
gesture swipe right 3 i3-msg focus right

gesture swipe up 3 i3-msg layout tabbed
gesture swipe down 3 i3-msg layout toggle split

gesture pinch out 3 i3-msg fullscreen enable
gesture pinch in 3 i3-msg fullscreen disable
